version: "3.9"

services:
  kafka:
    healthcheck:
      interval: 3s
    depends_on:
      primary-dekanat-db:
        condition: service_healthy
      secondary-dekanat-db:
        condition: service_healthy

  init-kafka:
    environment:
      - START_TIMEOUT=0s
  kafka-ui:
    profiles:
      - disabled
    ports: []

  primary-dekanat-db:
    image: ghcr.io/kneu-messenger-pigeon/dekanat-db-mock:main
    networks:
        - pigeon
    environment:
      - ISC_PASSWORD=test

  secondary-dekanat-db:
    image: ghcr.io/kneu-messenger-pigeon/dekanat-db-mock:main
    networks:
      - pigeon
    environment:
      - ISC_PASSWORD=test

  realtime-importer:
    environment:
      - PRIMARY_DEKANAT_DB_DSN=sysdba:test@primary-dekanat-db/dekanat.fdb?charset=UTF8
    depends_on:
      primary-dekanat-db:
        condition: service_healthy

  ### START section - secondary db importer ###
  secondary-db-disciplines-importer:
    environment:
      - SECONDARY_DEKANAT_DB_DSN=sysdba:test@secondary-dekanat-db/dekanat.fdb?charset=UTF8
    depends_on:
      secondary-dekanat-db:
        condition: service_healthy

  secondary-db-lessons-importer:
    environment:
      - SECONDARY_DEKANAT_DB_DSN=sysdba:test@secondary-dekanat-db/dekanat.fdb?charset=UTF8
    depends_on:
      secondary-dekanat-db:
        condition: service_healthy

  secondary-db-scores-importer:
    environment:
      - SECONDARY_DEKANAT_DB_DSN=sysdba:test@secondary-dekanat-db/dekanat.fdb?charset=UTF8
    depends_on:
      secondary-dekanat-db:
        condition: service_healthy

  ### END section - secondary db importer ###

  authorizer:
    ports: []
    environment:
      - KNEU_BASE_URI=http://${INTEGRATION_TEST_HOST:-integration-test}:8091

  telegram-app:
    environment:
      - TELEGRAM_URL=http://${INTEGRATION_TEST_HOST:-integration-test}:8090

  healthcheck-pinger:
    profiles:
      - disabled
    environment:
      - HEALTHCHECK_URL=https://${INTEGRATION_TEST_HOST:-integration-test}:8095/test-monitor1
