version: "3.9"

services:
  integration-testing:
    image: ghcr.io/kneu-messenger-pigeon/integration-testing:main
    networks:
      - pigeon
    environment:
        - KAFKA_HOST=kafka:9092
        - PRIMARY_DEKANAT_DB_DSN=sysdba:test@primary-dekanat-db/dekanat.fdb?charset=UTF8
        - SECONDARY_DEKANAT_DB_DSN=sysdba:test@secondary-dekanat-db/dekanat.fdb?charset=UTF8
        - DEBUG_UPDATES=true
        - PUBLIC_URL=${PUBLIC_URL}
        - KNEU_BASE_URI=http://${INTEGRATION_TEST_HOST:-integration-testing}:8091
        - KNEU_CLIENT_ID=${KNEU_CLIENT_ID}
        - KNEU_CLIENT_SECRET=${KNEU_CLIENT_SECRET}
        - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    depends_on:
      kafka:
        condition: service_started


  kafka:
    healthcheck:
      interval: 3s
    depends_on:
      primary-dekanat-db:
        condition: service_healthy
      secondary-dekanat-db:
        condition: service_healthy

  init-kafka:
    environment:
      - START_TIMEOUT=3s

  kafka-ui:
    profiles:
      - disabled
    ports: []

  primary-dekanat-db:
    image: ghcr.io/kneu-messenger-pigeon/dekanat-db-mock:main
    networks:
        - pigeon
    environment:
      - ISC_PASSWORD=test

  secondary-dekanat-db:
    image: ghcr.io/kneu-messenger-pigeon/dekanat-db-mock:main
    networks:
      - pigeon
    environment:
      - ISC_PASSWORD=test

  realtime-importer:
    environment:
      - PRIMARY_DEKANAT_DB_DSN=sysdba:test@primary-dekanat-db/dekanat.fdb?charset=UTF8
    depends_on:
      primary-dekanat-db:
        condition: service_healthy

  ### START section - secondary db importer ###
  secondary-db-watcher:
    environment:
      - SECONDARY_DEKANAT_DB_DSN=sysdba:test@secondary-dekanat-db/dekanat.fdb?charset=UTF8
      - PAUSE_AFTER_SUCCESS=60
      - PAUSE_AFTER_ERROR=2
      - ERROR_COUNT_TO_BREAK=5
    depends_on:
      secondary-dekanat-db:
        condition: service_healthy


  secondary-db-disciplines-importer:
    environment:
      - SECONDARY_DEKANAT_DB_DSN=sysdba:test@secondary-dekanat-db/dekanat.fdb?charset=UTF8
    depends_on:
      secondary-dekanat-db:
        condition: service_healthy

  secondary-db-lessons-importer:
    environment:
      - SECONDARY_DEKANAT_DB_DSN=sysdba:test@secondary-dekanat-db/dekanat.fdb?charset=UTF8
    depends_on:
      secondary-dekanat-db:
        condition: service_healthy

  secondary-db-scores-importer:
    environment:
      - SECONDARY_DEKANAT_DB_DSN=sysdba:test@secondary-dekanat-db/dekanat.fdb?charset=UTF8
    depends_on:
      secondary-dekanat-db:
        condition: service_healthy

  ### END section - secondary db importer ###

  authorizer:
    environment:
      - KNEU_BASE_URI=http://${INTEGRATION_TEST_HOST:-integration-testing}:8091

  telegram-app:
    environment:
      - TELEGRAM_URL=http://${INTEGRATION_TEST_HOST:-integration-testing}:8090

  healthcheck-pinger:
    profiles:
      - disabled
    environment:
      - HEALTHCHECK_URL=https://${INTEGRATION_TEST_HOST:-integration-testing}:8095/test-monitor1
