name: Integration testing

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      OVPN_CLIENT_KEY:
        required: true
      SSH_KEY:
        required: true
      INFISICAL_TOKEN_INTEGRATION_TEST:
        required: true

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ github.event_name }}
      - uses: actions/download-artifact@v3
        if: ${{ github.event_name == 'workflow_call' }}
        with:
          name: docker-compose.prod.yml

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: |
            Host remote
              HostName ${{ vars.SSH_HOST }}
              User ${{ vars.SSH_USER }}
              StrictHostKeyChecking no
      - name: Run integration test
        run: echo "Integration!"
