name: Deploy production

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      OVPN_CLIENT_KEY:
        required: true
      SSH_KEY:
        required: true
      INFISICAL_TOKEN_PRODUCTION:
        required: true
      CONTAINER_REGISTRY_READ_TOKEN:
        required: true

concurrency:
  group: production-deploy
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy production
    runs-on: ubuntu-latest
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@v1.3.0
        with:
          packages: openvpn openvpn-systemd-resolved
          version: 1.0
      - name: Write OVPN config
        run: printf "${{ vars.OVPN_CONFIG }}" > client.ovpn
      - name: Connect to VPN
        uses: kota65535/github-openvpn-connect-action@v2
        with:
          config_file: client.ovpn
          client_key: ${{ secrets.OVPN_CLIENT_KEY }}
      - name: Execute deploy on production server
        uses: appleboy/ssh-action@v0.1.10
        env:
          COMPOSE_URL: https://${{ github.token }}@raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/docker-compose.prod.yml
          INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN_PRODUCTION }}
          WORKDIR: ${{ vars.REMOTE_PROD_DIR }}
          DOCKER_USER: ${{ github.repository_owner }}
          DOCKER_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_READ_TOKEN }}
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: COMPOSE_URL,INFISICAL_TOKEN,WORKDIR,REF,DOCKER_USER,DOCKER_PASSWORD
          script_stop: true
          script: |
            grep '"ghcr.io"' ~/.docker/config.json || echo $DOCKER_PASSWORD | docker login ghcr.io -u "$DOCKER_USER" --password-stdin
            mkdir -p "$WORKDIR" && cd "$WORKDIR"
            [ -f docker-compose.yml ] && docker compose down || true
            curl --fail -s $COMPOSE_URL > docker-compose.yml
            docker compose pull --quiet
            docker compose build --quiet
            docker compose down
            docker compose up -d

            sleep 5
            curl --fail -s  http://"$(docker compose port authorizer 80)"/healthcheck
