name: Deploy to production

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: production-deploy
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
      - run: echo "Production deploy"
