name: Run integration testing and commit stable images digest

on:
  push:
    branches: ['main']
    paths-ignore:
      - docker-compose.prod.yml

  workflow_dispatch:

jobs:
  make-docker-compose-prod:
    name: Make docker-compose.prod.yml
    runs-on: ubuntu-latest
    outputs:
      change_detected: ${{ steps.detect-changes.outputs.change_detected }}
    steps:
       - uses: actions/checkout@v3
       - uses: chrisdickinson/setup-yq@latest
       - uses: imjasonh/setup-crane@v0.1
       - name: Log in to Docker Hub
         uses: docker/login-action@v2.1.0
         with:
           registry: ghcr.io
           username: ${{ github.repository_owner }}
           password: ${{ github.token }}

       - name: Make docker-compose.prod.yml
         run: ./bin/make-docker-compose-prod.sh

       - name: Detect diff in git diff --name-status  docker-compose.prod.yml
         id: detect-changes
         run: git diff --name-status docker-compose.prod.yml | grep docker-compose.prod.yml && echo "change_detected=1" >> $GITHUB_OUTPUT

       - uses: actions/upload-artifact@v3
         with:
          name: docker-compose.prod.yml
          path: docker-compose.prod.yml

  commit-docker-compose-prod:
    name: Commit docker-compose.prod.yml
    runs-on: ubuntu-latest
    needs:
     - make-docker-compose-prod
    if: ${{ needs.make-docker-compose-prod.outputs.change_detected }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: docker-compose.prod.yml
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: 'docker-compose.prod.yml'
          author_name: CI/CD bot
          committer_name: CI/CD bot
          fetch: false
          message: 'Updated docker-compose.prod.yml'
